// <auto-generated />
using Innkeep.Server.Db.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Innkeep.Server.Db.Migrations
{
    [DbContext(typeof(InnkeepServerContext))]
    [Migration("20240530193822_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Innkeep.Server.Db.Models.PretixConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("PretixAccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedEventName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedEventSlug")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedOrganizerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedOrganizerSlug")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PretixConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
